### ISSUE TITLE
[UI] Collection page, pagination empty button

### ISSUE THREAD

**Issue by maicss** [mongo-express/mongo-express#1363]
![image](https://github.com/mongo-express/mongo-express/assets/9784767/6a67afeb-df3f-4b8b-81dc-ecb20e6d8d99)

```
MongoDB Version | 4.4.25
com.docker.compose.version | 2.20.2
MONGO_EXPRESS_VERSION | 1.0.0
```

All marked yellow buttons are malfunction, and before pagination `1,2,3` there are two empty buttons.

**Comment by tusx** [comment]
+1 
Can confirm that i'm also having the same issues.
i'm using the latest Tag docker image.
![ss1](https://github.com/mongo-express/mongo-express/assets/33265258/ba5955a6-e7e0-4349-ad03-e23066d2584f)

**Comment by tusx** [comment]
seems like an issue was already created here https://github.com/mongo-express/mongo-express-docker/issues/104 and was fixed in this pull request https://github.com/mongo-express/mongo-express-docker/pull/108
i just updated the container from the latest Tag to mongo-express:1.0.2-20-alpine3.19 and it is working working for me.
@maicss you might wanna close this issue because it is already fixed.

**Comment by maicss** [comment]
OK，thanks a lot
