### ISSUE TITLE
Content Security Policy (CSP) blocks access to collections page

### ISSUE THREAD

**Issue by nazariifenii** [mongo-express/mongo-express#1665]
I'm using the mongo-express middleware, I'm starting the server and I can see the UI and list of collections, but when I'm navigating to the collection the page is refreshed and does not navigate to the collection (stays on the same page of list of collections). When I'm trying to export the collection - I'm redirected to 502 Bad Gateway.

**Comment by rtritto** [comment]
Can you provide logs?

**Comment by rtritto** [comment]
FYI @BlackthornYugen @xTudoS @shakaran

**Comment by SleepyDeb** [comment]
@nazariifenii can you provide a simple script that present the issue? I suspect it is something related to your express filters chain... If you could please copy the curl comand from your browser and execute it on bash adding "-vvv" we may be able to get some clue

**Comment by SleepyDeb** [comment]
First you have to enable the option requests on your api gateway to make it work..

second you have to setup the cors express middleware ..

the reason why you are encountering this issue only on the sub pages it’s because they use ajax to obtain data in page so the browser had to perform the preflight checks.

anyway, not related to this library. @rtritto i think you can close this.

**Comment by SleepyDeb** [comment]
Just to be clear, hosting mongo express inside aws lambda it is not something I can recommend, and for sure it’s not a use case supported directly by who wrote this software. If you are serious about hosting it in AWS (as I did) you should consider the idea to host it using ECS fargate.

**Comment by rtritto** [comment]
Thanks SleepyDeb for the answers.

Closing the issue.
