### ISSUE TITLE
Not support mongodb 3.2.3?

### ISSUE THREAD

**Issue by zeusro** [mongo-express/mongo-express#220]
After editing the config.js,it seems like I can connect the mongoDB server ,but when I try to add a collection,it says
```
Something went wrong: MongoError: not master and slaveOk=false
```

Also,it does not show the collection in the database correctly.

so I use the mongo shell to  check something

![image](https://cloud.githubusercontent.com/assets/5803609/14842464/1c6d247a-0c7a-11e6-9e0b-a85fae7f8ea2.png)

By the way,this issue does not happen if I use mongochef (another mongo connection GUI  client)

Anything wrong?

**Comment by wulfsolter** [comment]
That means you're trying to read from a secondary node in a replica set, you can only read from the primary node by default.

You can allow a secondary node to accept reads by running rs.slaveOk() in a mongo shell that is connected to that secondary node. Allowing reads from a secondary is not recommended, because you could be reading stale data if the node isn't yet synced with the primary node.

Your database configuration issues are not a mongo-express issue. Please read the [MongoDB Manual](https://docs.mongodb.org/manual/) or consult [the[1]](https://stackoverflow.com/questions/8990158/mongodb-replicates-and-error-err-not-master-and-slaveok-false-code?lq=1) [many[2]](https://stackoverflow.com/questions/17153813/mongodb-replica-set-preventing-queries-to-secondary) [copies[3]](https://stackoverflow.com/questions/30088833/strange-mongodb-and-mongoose-error-not-master-and-slaveok-false-error) [of[4]](https://stackoverflow.com/questions/21662203/uncaught-exception-error-err-not-master-and-slaveok-false-code-1) [this[5]](https://stackoverflow.com/questions/15345539/connecting-to-mongo-in-replica-set-mode) on [StackOverflow](https://stackoverflow.com/questions/tagged/mongodb) if you need more help on how to set up your DB properly.
