### ISSUE TITLE
Attempts to list databases even though admin is disabled

### ISSUE THREAD

**Issue by rubenvereecken** [mongo-express/mongo-express#228]
I got the following error:

```
{ [MongoError: not authorized on admin to execute command { listDatabases: 1 }]
  name: 'MongoError',
  message: 'not authorized on admin to execute command { listDatabases: 1 }',
  ok: 0,
  errmsg: 'not authorized on admin to execute command { listDatabases: 1 }',
  code: 13 }
```

even though `mongodb.admin` is disabled and I have a single element in the `mongodb.auth`  array that is allowed access to a single database. Everything works as I expected it to, there's just no need for it to still try things it's not allowed. Is this normal behavior?

I use the library as Express middleware and configure it by defining my own configuration, then adding in all the defaults that I haven't defined from your `config.default.js`.

**Comment by wulfsolter** [comment]
Update to latest and let me know if still persists (or worse yet, breaks things)

**Comment by gyratorycircus** [comment]
I'm encountering this exact issue, tested on both 0.30 and 0.31 releases.

In the homepage route of `routes/index.js`, `typeof req.adminDb === 'undefined'` never appears to be true, so instead of rendering the homepage immediately, it always attempts `req.adminDb.serverStatus`. 

This is the case since the adminDb is set on every request in the `mongoMiddleware` function of `router.js`, and that adminDb originates in `db.js`in the `connect` function. 

I'm wondering if the adminDb should only be populated after the `config.mongodb.admin === true` check on line 112, instead of where its originally defined on line 42 (`let adminDb   = db.admin();`).

[PR created](https://github.com/mongo-express/mongo-express/pull/253) along those lines.

**Comment by dozoisch** [comment]
This seems to be solved.
