### ISSUE TITLE
Receive an error "Cannot GET /mongo-express" (404 not found)

### ISSUE THREAD

**Issue by lihaibh** [mongo-express/mongo-express#239]
Ive established an environment via Vagrant on my Windows machine.
followed the guidance via your readme file and installed mongo-express app.
Im using pm2 (process manager for node apps) in order to run all my apps
I also use nginx as my web server that is used as http proxy to the app.
So everything fine, i started all the services go to the web page to view the panel and i receive an error: "Cannot GET /mongo-express" (404 not found error) i tried to fix that myself with no success.

Here what i see in the log file:
Mongo Express server listening at http://localhost:8081
Database connected
Connecting to admin...
Database admin connected
GET /mongo-express 404 21.957 ms - 26
GET /mongo-express 404 4.791 ms - 26

I searched up for this error and people say that it is associated with the express routing system occasionally about inconsistency of versions..

A little information about my system:
OS: Centos 7.1
node version: v6.2.1
npm version: 3.9.5
pm2 version: 1.1.3
Nginx version: 1.11.1
Mongodb version: 3.0.12

**Comment by knickers** [comment]
Are you trying to access `http://localhost:8081/mongo-express`? The index page should be `/` not `/mongo-express`, so the full url would be just `http://localhost:8081`

**Comment by lihaibh** [comment]
My config file in nginx is such so i assume it is ok:
server {
 listen 80;
 server_name local.www;
 location /mongo-express {
    alias /usr/local/lib/node_modules/mongo-express;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header Host $http_host;
    proxy_set_header X-NginX-Proxy true;
    proxy_pass http://127.0.0.1:8081;
    proxy_redirect off;
  }
}

now on my host machine im trying to access mongo-express via the url: local.www/mongo-express

**Comment by lihaibh** [comment]
@knickers you were right, i just didnt configure the nginx properly.
I had to rewrite url so mongo-express will receive another url so i added the line:
rewrite ^/mongo-express(.*) /$1 break; inside location block.
and now it loads as expected but i have nother issue that all the stylesheets could not be found because i rewrite the url lol:
http://local.www/stylesheets/bootstrap.min.css Failed to load resource: the server responded with a status of 404 (Not Found)

because the proxy is indie mongo-express location block.
so it doesnt fully resolved my issue, anyway it is nginx question and not mongo-express question.

**Comment by knickers** [comment]
Yeah, sorry. I probably won't be much help with nginx configs :smirk:.

And I could be totally wrong here, but in my experience, leaving the leading slash off URLs tells the browser to append the URL to the end of the current URL. For example `stylesheets/bootstrap.min.css` becomes `http://localhost:8081/db/local/stylesheets/bootstrap.min.css`. Whereas adding the leading slash tells the browser that this URL should be based at the root, so `stylesheets/bootstrap.min.css` becomes `http://localhost:8081/stylesheets/bootstrap.min.css`.

I don't know if this is relevant, but is it possible that the rewrite could be sending an extra slash at the beginning? Because `(.*)` will match a trailing slash and `/$1` adds a leading slash. `/mongo-express/stylesheets/bootstrap.min.css` would match `/stylesheets/bootstrap.min.css` as `$1` and be rewritten to `//stylesheets/bootstrap.min.css`.

**Comment by lihaibh** [comment]
Pay attention that nginx rewrite the full URL with the /mongo-express at the beginning so every url it catches from http://localhost:8081/mongo-express... 
Becomes http://localhost:8081/... Which is what mongo-express app expecting to get. 

However when it serves the html file the browser send a request back to the server with this path /stylesheets/bootstrap.min.css instead of
stylesheets/bootstrap.min.css

which is like telling the Web server 'I don't care in what url you are I want you to serve me this file from root'
