### ISSUE TITLE
JSCS/JSHINT

### ISSUE THREAD

**Issue by dozoisch** [mongo-express/mongo-express#265]
Hi!

When I ran JSCS/JSHINT when I did my pr, I got plenty of errors, like the tool had a hard time running. I'd be willing to upgrade your whole config to eslint (since JSCS merged into ESLINT anyway!) and configure it to run properly, etc. Is that something you would like?

**Comment by wulfsolter** [comment]
Yeah man!

Full disclaimer, my company ( http://wherewolf.co.nz/ ) has switched from a MongoDB+MySQL combo to full PostgreSQL, so apart from a few very very legacy systems which never get touched, I'm no longer running MongoDB in production and I'm very rarely needing a GUI for it. So.... I'm barely maintaining `mongo-express` these days.

I've since moved to `eslint` for most my active projects, it's a great tool and much nicer than JSCS/JSHint. :)

You have my full support and blessing!

**Comment by dozoisch** [comment]
Alright! Will send it this week!
