### ISSUE TITLE
Warning: connect.session() MemoryStore is not designed for a production

### ISSUE THREAD

**Issue by sobolevn** [mongo-express/mongo-express#276]
This warning is shown, when I use `mongo-express` as the `middleware`.

``` javascript
var mongoExpress = require('mongo-express/lib/middleware')
var mongoExpressConfig = require('./server/mongo-express-config')

// my sessions:
server.use(session({
  secret: process.env.SECRET_KEY,
  saveUninitialized: false,
  resave: false,
  store: new MongoStore({mongooseConnection: models.connection})
}));

server.use('/admin', mongoExpress(mongoExpressConfig))
```

Output:

> > node server.js
> 
> Warning: connect.session() MemoryStore is not
> designed for a production environment, as it will leak
> memory, and will not scale past a single process.
> Server is running at localhost:5000
> Database connected

I guess it happens with this line: https://github.com/mongo-express/mongo-express/blob/8dc6da59bf99f20f87bf2c2abb95db250fe57c33/lib/router.js#L41

**Comment by dozoisch** [comment]
Yeah, I guess the middleware shouldn't be the one handling session. It should be left in userland and documented when using the middleware.

**Comment by serge-nikitin** [comment]
So, is it a problem to use mongo-express as middleware in production? I have the same warning.

**Comment by KhalilKhalaf** [comment]
Ok looks like we can use some properties that can control this behavior: `interval`, `maxAge`, `cookie`, `saveUninitialized`, `resave` .. etc

More can be found here: [MongoDB fix: connection.session() MemoryStore is not designed for a production environment](https://digitalrizzle.wordpress.com/2013/04/26/mongodb-fix-connection-session-memorystore-is-not-designed-for-a-production-environment/)

Also that there are some hacks around this error, for example:

- Handle the error instead of crashing: https://stackoverflow.com/a/44884800/5890227

- use cookie-session instead of express-session: https://stackoverflow.com/a/37022764/5890227

- And/Or to force-clean all sessions in a custom function on our own: https://stackoverflow.com/a/10761522/5890227

I had same issue and did a quick research which is worth sharing. Hope it helps!

**Comment by rtritto** [comment]
@dozoisch 
Can be fixed with [memorystore](https://www.npmjs.com/package/memorystore).

`/lib/router.js` file:
```diff
const session = require('express-session');
+ const MemoryStore = require('memorystore')(session);
...
appRouter.use(session({
    ...
+    store: new MemoryStore({
+        checkPeriod: 86400000 // prune expired entries every 24h
+    }),
}));
```
