### ISSUE TITLE
Add delete button confirm

### ISSUE THREAD

**Issue by ggiacomo** [mongo-express/mongo-express#337]
Hi,
this tool is really great! But may I suggest one big issue?
In the view record, the delete button is too close to the back button, and there's no confirm dialog! argh!!!
For production uses, giving access someone not tech(e.s an account manager), this can be a disaster
http://prntscr.com/f1n15u
Is there a chance to add an extra confirm dialog?
Thank you!

**Comment by wulfsolter** [comment]
My 2 cents: I hate confirmation dialogs - it's not hard to be an adult, to take accountability for your actions, to take responsibility for what you do, to only click on things you actually mean to do. I do not think that "not tech" is any excuse for selecting a button that clearly says "Delete" on it, and is even RED for danger. Disasters only happen when you let idiots loose without proper education. Your "account manager" is hopefully not malicious, only under-educated. If a user clicking a delete is a "disaster", your automated and incremental backup system needs work.

Mongo-express was developed as a tool for power users to quickly do what they needed to do. It's not an idiot proof CMS. There have been plenty of requests from unskilled developers, and many many forks by competent developers where features have been turned off, UIs created for "author" level roles, and other dumbing down and removal of power features. I'm skeptical of ME's "idiot proof-ness" in general, there are many powerful features exposed to DBAs to get jobs done. If someone can't be trusted not to click the "Delete" button on a single document, how would a confirmation dialog solve anything? What's next, a confirmation dialog for "New" documents? A confirmation that a document edit was intentional? A confirmation that you wanted to navigate away from the current view? A confirmation that an index gets dropped?

If I use a knife, I expect it to be sharp. An untrusted / "not tech" user should not be editing on the raw production database! Build them a CMS! When I edit something in the raw database, I expect my actions to count. Catering to the lowest common denominator of idiots and molly-coddling the incompetent results in why the children of today have playgrounds that suck. 

Suggestion: Fork, and turn off all the other features that the untrusted don't need, and then you have an easy CMS. Easy. FWIW, adding a CSS override of `.btn-danger { display: none; }` would hide all red delete/danger buttons.

**Comment by MikeyBurkman** [comment]
I respectfully very strongly disagree with that sentiment. What's the difference between this and the "new document" button? Simple! You can delete the new document, undo-ing what you just accidentally did! That comparison is asinine. Same with the knife argument. The knife NEEDS to be sharp to do its job. But if there was a way to add a "Did you mean to slice your finger?" confirmation dialog to a knife, you bet your ass I totally would love to have it.

Mistakes happen. I don't care how much of an "adult" you are. If you accidentally delete some record in production instead of clicking the back button because you're doing prod support at 3am and now you have to explain to your boss in the morning that you just deleted a customer document and it's unrecoverable, you're going to REALLY wish you had used a more helpful tool. Honestly, what's the point of using Mongo Express over the CLI if it's not there to help you?

Anything that is easy to do (like in one inadvertent click), and isn't undoable, should definitely have either a confirmation dialog. If YOU want to be a "power user" then use the CLI. (Or maybe YOU should be the one forking the repo and removing all the nice usability features that you hate so much.)

**Comment by wulfsolter** [comment]
Noted :) I'm not entirely sure why anyone would ever be editing on a prod server *without backups*, as that's a pretty big failure of procedures, forward thinking and planning. I guess maybe I'm cynical enough that I run more conservatively than many and set up backups very soon after the first `git init`.

For what it's worth, I [added most of the idiot proof eye candy we love so much](https://github.com/mongo-express/mongo-express/graphs/contributors) but somewhere I think we need to draw the line between a CMS for idiots and a useful tool that empowers. ME is a powerful tool that is quicker than CLI for custom/bespoke DBA work. I feel it's "doing it wrong" when you ask non-tech to use a tool like ME or PhpMyAdmin.

That said, if someone wants to write a PR I'll support it and merge, all I'd ask is that this hand-holding functionality can be turned off easily. Like [PhpMyAdmin's config](https://docs.phpmyadmin.net/en/latest/config.html#cfg_Confirm) for example.

If I take @MikeyBurkman's thoughts further, maybe the best solution would be an "undo stack"? As there's no native MongoDB functionality to handle this, I could see something like a (n) deep stack that "moves" rather than "drops". Pretty big undertaking, but would make many people happy at once...

**Comment by MikeyBurkman** [comment]
Yeah I think you're making too many assumptions about the users :) In my case, I set this up with my client for a few of their databases specifically so they could do prod support. (They're techy, but certainly not Mongo DBAs.) We're actually using a SaaS product that doesn't give us great CLI access, so this was actually the best option. The Saas does take backups, but I'm not certain how often, and it involves opening a support ticket, which is a bit of a hassle. Not ideal but it's what we got. When I initially showed ME to my client, they were at first very worried about how large the delete icons were, until I showed them that there was indeed a confirmation dialog :)

If you really want to get rid of the dialogs, I'd rather just have a config option to do so. Or have some user- or session-specific setting. But I'd be shocked if many users wanted no-dialog to be the default.

An undo stack, even of depth one, would be awesome, but could be quite difficult. Does the option simply do the inverse of what was called? This is pretty easy with deleting individual documents, but deleting indexes or entire collections could be extremely slow or simply unfeasible. (Moving/renaming for collections is a better option, but still an undertaking, and not guaranteed to be conflict-free.)

Another option is what I would call the gmail undo, where you have a little toast appear at the top that lets you undo the last action. An easy-ish implementation would be to just queue up the deletion command, and then execute it either at the end of a timer, or when the toast is removed from the page (usually because the user navigates away). If the user clicks undo, the queued-up command is simply deleted. I think that's probably easier, but still a considerable undertaking that I'm not sure many have time to do.

**Comment by bert-w** [comment]
support for confirmation popup on every delete button. Delete actions should be protected from invalid clicks at all times.

If for some reason you need to remove 25 records and you dont want to press 25 buttons and 25 dialogs, the interface needs to be remade into checkbox style, so you can select 25 and remove them all at once (with confirmation ofcourse)

**Comment by wulfsolter** [comment]
as mentioned before, @bert-w, PRs are welcome.... Support ideas with actions.

**Comment by bert-w** [comment]
when i have time i will, i like this package but also got some improvements (for instance the whole layout is very big and takes up a lot of room for very little actions)

**Comment by chrisdamba** [comment]
@dozoisch [Commit](https://github.com/mongo-express/mongo-express/commit/5f8c28fd6415377fdfa49e95b2d535fea50621c8) fixed this issue

**Comment by dozoisch** [comment]
@chrisdamba you are right :), closing!
