### ISSUE TITLE
How to use the "simple" search?

### ISSUE THREAD

**Issue by warhost** [mongo-express/mongo-express#343]
Hey, 

this might look dumb to some here, but I can't seem to figure out the correct syntax for the search.
When I enter "_id" without the quotes into the Key field, and 50 in the value field, I expect that the row with _id entry 50 shows up. But it doesn't, it says it didn't find anything.

Whats wrong with this query?

**Comment by dozoisch** [comment]
Hey! Here is an example:

![image](https://cloud.githubusercontent.com/assets/4422516/26036746/80da61ca-3898-11e7-8648-e322dfd34367.png)


You have to set the type field to ObjectID so that it knows that it needs to wrap the value like this ` ObjectID("5655387462d388d0088bec6c")` when doing the research.

**Comment by warhost** [comment]
Hey, thanks for reply.
Honestly it still doesn't work for me.

I am getting "ObjectID(...) wrapper must be present" when doing exactly what you you are doing.

**Comment by dozoisch** [comment]
Oh I assumed your Ids were mongo objectID, but it seems like you are using numerical ids instead.
