### ISSUE TITLE
Import collection with date is not working

### ISSUE THREAD

**Issue by LucasBrazi06** [mongo-express/mongo-express#422]
I have a collection issued by 'mongoexport' provided by MongoDB and I try to import it using your app.

This collection contains dates in a format that you do not support:

> "createdOn": {
>             "$date": "2017-09-02T08:07:00.069Z"
> }

And you expect this:

> "createdOn": "2017-09-02T08:07:00.069Z"

Could you provide a fix?

**Comment by dozoisch** [comment]
Hi @LucasBrazi06, if you have time to submit a PR that would be much appreciated. Here is the PR https://github.com/mongo-express/mongo-express/pull/421 that added this feature as a reference. 

Otherwise, I unfortunately don't really have the bandwidth to do it in the next few days, so it'll have to go later. 

Unless... @Duvieusam I'don't know if you have bandwidth for this as your are the one who added the import! :)

**Comment by LucasBrazi06** [comment]
The PR #421 is closed.

**Comment by dozoisch** [comment]
@LucasBrazi06 yes, it was the PR where that feature was added
