### ISSUE TITLE
delete-all-documents destroys index definition

### ISSUE THREAD

**Issue by osher** [mongo-express/mongo-express#498]
## Scenario:

Enter a DB
Setup a target collection in a test db:
  - make sure there are documents in the collection
  - make sure there are few user-indexes defined

In mongo-express
enter the test db
enter the target collection
Observe the red "delete all # documents" on screen with number of docs in the collection
Click the "delete all # documents"

## expected

The documents should be deleted
User Index definitions should be preserved

## found
the entire collection is dropped, together with it's user-index definitions.

**Comment by osher** [comment]
If the button drops the collection - then name it so.

BTW - I think both variants would be useful
i.e - a **_drop collection_** button, and a **_empty collection_** button

**Comment by Premik** [comment]
This only happens when the query has no conditions. I.e. in case all documents get matched by the query. Then the whole collection gets dropped instead of just the data.. This is defo a bug.

I also personally found it bit annoying there is big red "`Delete all` button full-view-width right below the `Find` button. Like if deleting all my data was something I do on daily basis :-) 

This button also have negative impact on expensive queries because there is always the `count` operation being run on top of the regular `findAll`. Where the `limit` doesn't help. On the other hand it is usually useful to see the number of matching documents.

**Comment by osher** [comment]
Well, you do delete all your data if you're a developer.
You got a huge collection that is part of some BI pipeline, it's big enough to require indexes, and as long as you develop your run you'd love to delete all documents **without destroying your indexes**, and you would do it few times an hour.

The thing is that with indexes your BI cycle is fast enough and you get results you can build on, and without indexes your BI pipline gets stuck, and you have to redo the indexes and tweak the code to start from where it failed, mnyeeeeh... 

by now as a developer I learnt not to touch this button, and delete all docs by other means, which involve a work-around which is almost a backdoor. but why the hussle?  we got the mongo-express accessible with vpn and wrapped with our own authentication, and there is such a beautiful button - if only it had worked.... :smile:

**Comment by dozoisch** [comment]
@oshr im open to a pr! The confirm dialog could have a checkbox on whether or not to include indexes in the drop. I don't have the bandwidth to do that kind of fix myself though.

**Comment by osher** [comment]
@dozoisch  - I hear your pain, and stand with you.
BTW - if I have the bandwidth, I usually go straight to PR...
lets see who gets to do that first
